# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: url.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'url.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\turl.proto\x12\x0e\x65\x64u.pucmm.grpc\"n\n\x05Stats\x12\x12\n\naccessedAt\x18\x01 \x01(\t\x12\x11\n\tipAddress\x18\x02 \x01(\t\x12\x0f\n\x07\x62rowser\x18\x03 \x01(\t\x12\n\n\x02os\x18\x04 \x01(\t\x12\x10\n\x08referrer\x18\x05 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\"\x1e\n\nUrlRequest\x12\x10\n\x08username\x18\x01 \x01(\t\"\x82\x01\n\tUrlRecord\x12\x13\n\x0boriginalUrl\x18\x01 \x01(\t\x12\x10\n\x08shortUrl\x18\x02 \x01(\t\x12\x11\n\tcreatedAt\x18\x03 \x01(\t\x12$\n\x05stats\x18\x04 \x03(\x0b\x32\x15.edu.pucmm.grpc.Stats\x12\x15\n\rpreviewBase64\x18\x05 \x01(\t\"?\n\x14ListUserUrlsResponse\x12\'\n\x04urls\x18\x01 \x03(\x0b\x32\x19.edu.pucmm.grpc.UrlRecord\"9\n\x10\x43reateUrlRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x13\n\x0boriginalUrl\x18\x02 \x01(\t\";\n\x11\x43reateUrlResponse\x12&\n\x03url\x18\x01 \x01(\x0b\x32\x19.edu.pucmm.grpc.UrlRecord2\xb0\x01\n\nUrlService\x12P\n\x0cListUserUrls\x12\x1a.edu.pucmm.grpc.UrlRequest\x1a$.edu.pucmm.grpc.ListUserUrlsResponse\x12P\n\tCreateUrl\x12 .edu.pucmm.grpc.CreateUrlRequest\x1a!.edu.pucmm.grpc.CreateUrlResponseB#\n\x0e\x65\x64u.pucmm.grpcB\x0fUrlServiceProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'url_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016edu.pucmm.grpcB\017UrlServiceProtoP\001'
  _globals['_STATS']._serialized_start=29
  _globals['_STATS']._serialized_end=139
  _globals['_URLREQUEST']._serialized_start=141
  _globals['_URLREQUEST']._serialized_end=171
  _globals['_URLRECORD']._serialized_start=174
  _globals['_URLRECORD']._serialized_end=304
  _globals['_LISTUSERURLSRESPONSE']._serialized_start=306
  _globals['_LISTUSERURLSRESPONSE']._serialized_end=369
  _globals['_CREATEURLREQUEST']._serialized_start=371
  _globals['_CREATEURLREQUEST']._serialized_end=428
  _globals['_CREATEURLRESPONSE']._serialized_start=430
  _globals['_CREATEURLRESPONSE']._serialized_end=489
  _globals['_URLSERVICE']._serialized_start=492
  _globals['_URLSERVICE']._serialized_end=668
# @@protoc_insertion_point(module_scope)
